// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwndYncuUx_RJY-rcJ1mOKuhKDJBAf8og',
    appId: '1:445607731202:web:990c7ed01b873d9dd4c71b',
    messagingSenderId: '445607731202',
    projectId: 'trackit-f1422',
    authDomain: 'trackit-f1422.firebaseapp.com',
    storageBucket: 'trackit-f1422.firebasestorage.app',
    measurementId: 'G-S3D1YLQ55E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaoeAZKG3CjjuGDDqce5SbDnRgXY026H4',
    appId: '1:445607731202:android:fc58c96c19043c1cd4c71b',
    messagingSenderId: '445607731202',
    projectId: 'trackit-f1422',
    storageBucket: 'trackit-f1422.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChgvB6lID_Myx7pnBGgZgCYdijt2pkb_g',
    appId: '1:445607731202:ios:072eee59a7e6771ad4c71b',
    messagingSenderId: '445607731202',
    projectId: 'trackit-f1422',
    storageBucket: 'trackit-f1422.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChgvB6lID_Myx7pnBGgZgCYdijt2pkb_g',
    appId: '1:445607731202:ios:072eee59a7e6771ad4c71b',
    messagingSenderId: '445607731202',
    projectId: 'trackit-f1422',
    storageBucket: 'trackit-f1422.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwndYncuUx_RJY-rcJ1mOKuhKDJBAf8og',
    appId: '1:445607731202:web:7396eed5dec607d7d4c71b',
    messagingSenderId: '445607731202',
    projectId: 'trackit-f1422',
    authDomain: 'trackit-f1422.firebaseapp.com',
    storageBucket: 'trackit-f1422.firebasestorage.app',
    measurementId: 'G-YRMXFMB3H1',
  );
}
